name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      - uses: actions/setup-python@v4
        with:
            python-version: '3.11.2'
            
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          sudo -H pip3 install -r requirements.txt
          python3 train.py
          #write everything into a markdown and then return it into github
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md

          echo "## Data vis" >> report.md
          echo "![](./feature_importance.png)" >> report.md 
          echo "![](./residuals.png)" >> report.md
          
          cml comment create report.md
